// Code generated by protoc-gen-go. DO NOT EDIT.
// source: example/example.proto

package example

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/srikrsna/protoc-gen-gotag/tagger"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Example struct {
	WithNewTags     string `protobuf:"bytes,1,opt,name=with_new_tags,json=withNewTags,proto3" json:"with_new_tags,omitempty" graphql:"withNewTags,optional"`
	WithNewMultiple string `protobuf:"bytes,2,opt,name=with_new_multiple,json=withNewMultiple,proto3" json:"with_new_multiple,omitempty" graphql:"withNewTags,optional" xml:"multi,omitempty"`
	ReplaceDefault  string `protobuf:"bytes,3,opt,name=replace_default,json=replaceDefault,proto3" json:"replacePrevious"`
	// Types that are valid to be assigned to OneOf:
	//	*Example_A
	//	*Example_BJk
	OneOf                isExample_OneOf `protobuf_oneof:"one_of" graphql:"withNewTags,optional"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-" graphql:"-" bson:"-"`
	XXX_unrecognized     []byte          `json:"-" graphql:"-" bson:"-"`
	XXX_sizecache        int32           `json:"-" graphql:"-" bson:"-"`
}

func (m *Example) Reset()         { *m = Example{} }
func (m *Example) String() string { return proto.CompactTextString(m) }
func (*Example) ProtoMessage()    {}
func (*Example) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c78cffa5d645ba4, []int{0}
}

func (m *Example) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Example.Unmarshal(m, b)
}
func (m *Example) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Example.Marshal(b, m, deterministic)
}
func (m *Example) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Example.Merge(m, src)
}
func (m *Example) XXX_Size() int {
	return xxx_messageInfo_Example.Size(m)
}
func (m *Example) XXX_DiscardUnknown() {
	xxx_messageInfo_Example.DiscardUnknown(m)
}

var xxx_messageInfo_Example proto.InternalMessageInfo

func (m *Example) GetWithNewTags() string {
	if m != nil {
		return m.WithNewTags
	}
	return ""
}

func (m *Example) GetWithNewMultiple() string {
	if m != nil {
		return m.WithNewMultiple
	}
	return ""
}

func (m *Example) GetReplaceDefault() string {
	if m != nil {
		return m.ReplaceDefault
	}
	return ""
}

type isExample_OneOf interface {
	isExample_OneOf()
}

type Example_A struct {
	A string `protobuf:"bytes,5,opt,name=a,proto3,oneof" json:"A"`
}

type Example_BJk struct {
	BJk int32 `protobuf:"varint,6,opt,name=b_jk,json=bJk,proto3,oneof" json:"b_Jk"`
}

func (*Example_A) isExample_OneOf() {}

func (*Example_BJk) isExample_OneOf() {}

func (m *Example) GetOneOf() isExample_OneOf {
	if m != nil {
		return m.OneOf
	}
	return nil
}

func (m *Example) GetA() string {
	if x, ok := m.GetOneOf().(*Example_A); ok {
		return x.A
	}
	return ""
}

func (m *Example) GetBJk() int32 {
	if x, ok := m.GetOneOf().(*Example_BJk); ok {
		return x.BJk
	}
	return 0
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Example) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Example_A)(nil),
		(*Example_BJk)(nil),
	}
}

type SecondMessage struct {
	WithNewTags          string   `protobuf:"bytes,1,opt,name=with_new_tags,json=withNewTags,proto3" json:"with_new_tags,omitempty" graphql:"withNewTags,optional"`
	WithNewMultiple      string   `protobuf:"bytes,2,opt,name=with_new_multiple,json=withNewMultiple,proto3" json:"with_new_multiple,omitempty" graphql:"withNewTags,optional" xml:"multi,omitempty"`
	ReplaceDefault       string   `protobuf:"bytes,3,opt,name=replace_default,json=replaceDefault,proto3" json:"replacePrevious"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" graphql:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" graphql:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" graphql:"-" bson:"-"`
}

func (m *SecondMessage) Reset()         { *m = SecondMessage{} }
func (m *SecondMessage) String() string { return proto.CompactTextString(m) }
func (*SecondMessage) ProtoMessage()    {}
func (*SecondMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c78cffa5d645ba4, []int{1}
}

func (m *SecondMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SecondMessage.Unmarshal(m, b)
}
func (m *SecondMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SecondMessage.Marshal(b, m, deterministic)
}
func (m *SecondMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SecondMessage.Merge(m, src)
}
func (m *SecondMessage) XXX_Size() int {
	return xxx_messageInfo_SecondMessage.Size(m)
}
func (m *SecondMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_SecondMessage.DiscardUnknown(m)
}

var xxx_messageInfo_SecondMessage proto.InternalMessageInfo

func (m *SecondMessage) GetWithNewTags() string {
	if m != nil {
		return m.WithNewTags
	}
	return ""
}

func (m *SecondMessage) GetWithNewMultiple() string {
	if m != nil {
		return m.WithNewMultiple
	}
	return ""
}

func (m *SecondMessage) GetReplaceDefault() string {
	if m != nil {
		return m.ReplaceDefault
	}
	return ""
}

func init() {
	proto.RegisterType((*Example)(nil), "example.Example")
	proto.RegisterType((*SecondMessage)(nil), "example.SecondMessage")
}

func init() { proto.RegisterFile("example/example.proto", fileDescriptor_1c78cffa5d645ba4) }

var fileDescriptor_1c78cffa5d645ba4 = []byte{
	// 319 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe4, 0x92, 0xc1, 0x4a, 0x33, 0x31,
	0x10, 0xc7, 0xbf, 0x6d, 0xbf, 0xb6, 0x9a, 0x52, 0xab, 0x11, 0x65, 0x51, 0x94, 0x12, 0x11, 0x7a,
	0xa8, 0xf6, 0xa0, 0x17, 0x7b, 0xb3, 0x54, 0x94, 0x42, 0x45, 0x56, 0xef, 0x4b, 0xb6, 0x9d, 0xa6,
	0xdb, 0x66, 0x37, 0x71, 0x93, 0xba, 0xf5, 0xae, 0x2f, 0xe1, 0xc1, 0xa7, 0xf4, 0x01, 0x24, 0x9b,
	0x20, 0x9e, 0xc4, 0xbb, 0xa7, 0x21, 0x93, 0xdf, 0xff, 0x37, 0x30, 0x0c, 0xda, 0x81, 0x15, 0x4d,
	0x24, 0x87, 0xae, 0xab, 0xa7, 0x32, 0x13, 0x5a, 0xe0, 0x9a, 0x7b, 0xee, 0x6d, 0x6b, 0xca, 0x18,
	0x64, 0x5d, 0x5b, 0xec, 0x2f, 0xf9, 0x28, 0xa1, 0xda, 0x95, 0x05, 0xf0, 0x35, 0x6a, 0xe4, 0xb1,
	0x9e, 0x85, 0x29, 0xe4, 0xa1, 0xa6, 0x4c, 0xf9, 0x5e, 0xcb, 0x6b, 0xaf, 0xf7, 0x8f, 0xde, 0x5e,
	0xde, 0xcb, 0x87, 0x2c, 0xa3, 0x72, 0xf6, 0xc8, 0x7b, 0xc4, 0x20, 0xb7, 0x90, 0x3f, 0x50, 0xa6,
	0x3a, 0x42, 0xea, 0x58, 0xa4, 0x94, 0x93, 0xa0, 0xfe, 0xad, 0x8d, 0x01, 0x6d, 0x7d, 0x89, 0x92,
	0x25, 0xd7, 0xb1, 0xe4, 0xe0, 0x97, 0x0a, 0xd9, 0x85, 0x91, 0x9d, 0xff, 0x2c, 0x6b, 0xad, 0x12,
	0xde, 0x23, 0x45, 0xb0, 0x23, 0x92, 0x58, 0x43, 0x22, 0xf5, 0x33, 0x09, 0x9a, 0x0e, 0x1e, 0x39,
	0x23, 0x1e, 0xa0, 0x66, 0x06, 0x92, 0xd3, 0x31, 0x84, 0x13, 0x98, 0xd2, 0x25, 0xd7, 0x7e, 0xb9,
	0x18, 0xb2, 0x6f, 0x86, 0xec, 0xce, 0x95, 0x48, 0x7b, 0xc4, 0x11, 0x77, 0x19, 0x3c, 0xc5, 0x62,
	0xa9, 0x48, 0xb0, 0xe1, 0x3a, 0x03, 0x1b, 0xc1, 0x07, 0xc8, 0xa3, 0x7e, 0xa5, 0xc8, 0x35, 0x4c,
	0x6e, 0xcd, 0xe6, 0x2e, 0xc9, 0xcd, 0xbf, 0xc0, 0xa3, 0xf8, 0x18, 0xfd, 0x8f, 0xc2, 0xf9, 0xc2,
	0xaf, 0xb6, 0xbc, 0x76, 0xa5, 0xbf, 0x69, 0x88, 0xba, 0x25, 0xa2, 0x70, 0xb8, 0x30, 0x50, 0x39,
	0x1a, 0x2e, 0xfa, 0x27, 0xa8, 0x2a, 0x52, 0x08, 0xc5, 0x14, 0xff, 0x66, 0x5d, 0xe4, 0xb5, 0x84,
	0x1a, 0xf7, 0x30, 0x16, 0xe9, 0x64, 0x04, 0x4a, 0x51, 0xf6, 0x47, 0x97, 0x1f, 0x55, 0x8b, 0x2b,
	0x3c, 0xfb, 0x0c, 0x00, 0x00, 0xff, 0xff, 0x18, 0x14, 0x82, 0x3f, 0xbc, 0x02, 0x00, 0x00,
}
